### ISSUE TITLE
Upgrade to passport-saml 1.0

### ISSUE THREAD

**Issue by oliver-nh** [molekilla/hapi-passport-saml#22]
Passport-saml 1.0 was released a few months ago. Any chance you'll upgrade this package to support it?

**Comment by molekilla** [comment]
Hi, was reviewing new passport-saml, it seems this will required a bit of work. If you have time send me the PR and I can review.

Thanks
Rogelio

**Comment by oliver-nh** [comment]
Sure, happy to help. I’m fairly busy this week, but I’ll let you know if I have some time to work on it this weekend.

**Comment by badraygun** [comment]
@molekilla can you close out this issue as I have added support for this?
