### ISSUE TITLE
Upgrade to hapi 17

### ISSUE THREAD

**Issue by BorntraegerMarc** [molekilla/hapi-passport-saml#9]
Will this plugin support hapi 17?

**Comment by molekilla** [comment]
We should probably have a 17 compatible release. Any kind soul who could
send me a PR and I will review it before pushing to npm? Thanks

**Comment by molekilla** [comment]
Another idea is that I setup a patreon fund page to get this out for those
interested. You can ping me at my Gmail email for more.
